autoscaling:
  enabled: false
replicaCount: 1
nameOverride: ""
fullnameOverride: ""
image:
  registry: "ghcr.io"
  repository: brokerua/kbot
  tag: v1.0.10-c6f2cf2
  os: linux
  arch: amd64
  pullPolicy: IfNotPresent
secret:
  name: "TELE_TOKEN"
  tokenKey: "token"
  tokenName: "kbot"
